### PR TITLE
[Feature] Add Support for HKR2 & HKR3

### PR DESCRIPTION
**Pull request by kwithus**
PR adds support for HKR2 & HKR3

### CODE REVIEW

**Comment by LarsK1** [comment]
Hi @kwithus ,
first of all many thanks for your pr. Unfortunately I can't merge it this way. You've uploaded the new files in the main directory. They should go here: https://github.com/kwithus/hass_solvis_control/tree/kwithus-patch-1/custom_components/solvis_control

Therefore please delete the uploaded files in the main dir and reupload them to the correct directory :)

Thanks a lot!

**Comment by LarsK1** [comment]
I've adjusted the files accordingly for you. Thanks for your work!

**Comment by kwithus** [comment]
Thanks for adjusting it! Hopefully I will do a better job next time. ;-)
I will try to suggest more changes.
More important: let’s cross fingers, that Solvis fixes the Modbus issues on their side asap.

**Comment by kwithus** [comment]
Hi I still struggle with with pull requests and uploading, sorry.I did over the weekend some changes, mainly adding all HKR with all temp and curve settings, including changing the names etc.I also added / changed the pumps for HKR1-3, including adjusting the correct measurements I uploaded the changed files to the directory you told me, but then I don’t know how to proceed.Best regardsKarlBeste GrüßeAm 06.10.2024 um 08:01 schrieb Lars Kusch ***@***.***>:﻿
Hi @kwithus ,
first of all many thanks for your pr. Unfortunately I can't merge it this way. You've uploaded the new files in the main directory. They should go here: https://github.com/kwithus/hass_solvis_control/tree/kwithus-patch-1/custom_components/solvis_control
Therefore please delete the uploaded files in the main dir and reupload them to the correct directory :)
Thanks a lot!

**Comment by LarsK1** [comment]
@kwithus just raise a new PR. Please start the title with "[Feature] Added XYZ" and give a short description about your changes".

Afterwards I will review and give you hints.

**Comment by kwithus** [comment]
When I try to raise a PR it says nothing to compare and I am not able to initiate a PR
image

**Comment by LarsK1** [comment]
@kwithus you'll need to select your feature-branch not main... (kwithus-patch-1)

**Pull request merged**
